### ISSUE TITLE
Changing Predator Mode does not alter GPU TGP

### ISSUE THREAD

**Issue by snowyoneill** [snowyoneill/Linux-PredatorSense#2]
In Windows when you switch between the predator profiles it changes the current GPU target TGP and therefore either draws more or less current.

On linux it seems the GPU is capped at 80W even though this laptop can go to 105W. Looks like this is a common issue for mobile GPUs: https://forums.developer.nvidia.com/t/has-anyone-been-able-to-run-an-rtx-3060-laptop-gpu-at-more-than-80w-on-linux/192959

Will require more investigation.

**Comment by gator-git** [comment]
I think, which is to be seen in the thread which you have displayed, flashing a different VBIOS might be the only solution now. Unless NVIDIA finds a solution for it. I might be completely wrong though.

**Comment by snowyoneill** [comment]
Yeah I've started taking a look into flashing the VBIOS with NVFlash. Just need to figure out the correct ROM to switch to and test to see if it has any unintended consequences.

**Comment by BrycensRanch** [comment]
Hello! I think this issue is fixed with NVIDIA's latest stable drivers. 

I myself used to be locked at 75W max on Ubuntu, however, daddy Nvidia dropped a update that seems to fix this.

My laptop is rated for 105W by Acer and during gaming it certainly hits it.

**NOTE**: I have nvidia-powerd configured and running properly, so this may play a factor. View the doc from Nvidia here https://download.nvidia.com/XFree86/Linux-x86_64/510.47.03/README/dynamicboost.html#:~:text=The%20nvidia-powerddaemon%20provides%20support%20for%20the%20NVIDIA%20Dynamic,and%20the%20CPU%2C%20Dynamic%20Boost%20can%20deliver%20more

![Screenshot_20230920_153356](https://github.com/snowyoneill/Linux-PredatorSense/assets/117921904/9d422755-2dd3-4791-97f6-56cb17222826)

![Screenshot_20230920_153050](https://github.com/snowyoneill/Linux-PredatorSense/assets/117921904/363fb253-44a1-4444-a2dd-48b45193893f)
![Screenshot_20230920_153439](https://github.com/snowyoneill/Linux-PredatorSense/assets/117921904/140a9339-6655-41da-baab-cfc35019c324)

**Comment by snowyoneill** [comment]
@BrycensRanch ohhhhhh thank you for this info!! I'll do some testing on my end to confirm. Currently on ubuntu driver version 535.86.05 and i can only go to 95W.

**Comment by snowyoneill** [comment]
@BrycensRanch i haven't yet tried to update to the newest sub version of the driver but according to the release notes I'm not sure that it will help. https://www.nvidia.com/download/driverResults.aspx/210649/en-us/

This was the release that extended support for dynamic boost on more notebooks.
https://www.nvidia.com/download/driverResults.aspx/205464/en-us/

Either way i'll give it a try and report back.

Quick question do you see any output for
```
nvidia-settings -q DynamicBoostSupport
```
I only seems to get `(Unrecognized attribute name)`

I do see 105W under `nvidia-smi -q` when `powerd-service` is running

```
GPU Power Readings
        Power Draw                        : 13.32 W
        Current Power Limit               : 80.00 W
        Requested Power Limit             : N/A
        Default Power Limit               : 80.00 W
        Min Power Limit                   : 1.00 W
        Max Power Limit                   : 105.00 W
```
But when i try and run the Unigine Heaven Benchmark i never draw more than 95W

**Comment by BrycensRanch** [comment]
Looking more depth into this, I've tried playing Minecraft with the most demanding shader, BSL with Ultra. 

It's very possible nvidia-powerd could be the missing piece, here. When I first installed NVIDIA drivers on KDE neon, I was limited to 75W. After troubleshooting and looking for this nvidia-powerd service everyone in the NVIDIA forums talks about, I found it via `find` so your mileage may vary. We do have the same laptop to my knowledge so it's interesting to see how it behaves. I installed a LOT of NVIDIA packages in hopes of fixing this issue.

```zsh
➜  ~ nala list --installed | grep nvidia
libnvidia-cfg1-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-common-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-compute-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-container-tools 1.14.1-1 [NVIDIA CORPORATION <cudatools@nvidia.com>/stable ]
libnvidia-container1 1.14.1-1 [NVIDIA CORPORATION <cudatools@nvidia.com>/stable ]
libnvidia-decode-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-encode-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-extra-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-fbc1-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-gl-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
libnvidia-ml-dev 11.5.50~11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
linux-modules-nvidia-535-6.2.0-32-generic 6.2.0-32.32~22.04.1 [Ubuntu/jammy restricted]
└── Linux kernel nvidia modules for version 6.2.0-32
linux-modules-nvidia-535-6.2.0-34-generic 6.2.0-34.34~22.04.1 [Ubuntu/jammy restricted]
└── Linux kernel nvidia modules for version 6.2.0-34
linux-modules-nvidia-535-generic-hwe-22.04 6.2.0-34.34~22.04.1 [Ubuntu/jammy restricted]
└── Extra drivers for nvidia-535 for the generic-hwe-22.04 flavour
linux-objects-nvidia-535-6.2.0-32-generic 6.2.0-32.32~22.04.1 [Ubuntu/jammy restricted]
└── Linux kernel nvidia modules for version 6.2.0-32 (objects)
linux-objects-nvidia-535-6.2.0-34-generic 6.2.0-34.34~22.04.1 [Ubuntu/jammy restricted]
└── Linux kernel nvidia modules for version 6.2.0-34 (objects)
linux-signatures-nvidia-6.2.0-32-generic 6.2.0-32.32~22.04.1 [Ubuntu/jammy restricted]
└── Linux kernel signatures for nvidia modules for version 6.2.0-32-generic
linux-signatures-nvidia-6.2.0-34-generic 6.2.0-34.34~22.04.1 [Ubuntu/jammy restricted]
└── Linux kernel signatures for nvidia modules for version 6.2.0-34-generic
nvidia-compute-utils-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
nvidia-container-toolkit 1.14.1-1 [NVIDIA CORPORATION <cudatools@nvidia.com>/stable ]
nvidia-container-toolkit-base 1.14.1-1 [NVIDIA CORPORATION <cudatools@nvidia.com>/stable ]
nvidia-cuda-dev 11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
nvidia-cuda-gdb 11.5.114~11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
nvidia-cuda-toolkit 11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
nvidia-cuda-toolkit-doc 11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
nvidia-dkms-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
nvidia-driver-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
nvidia-firmware-535-535.104.05 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
nvidia-kernel-common-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
nvidia-kernel-source-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
nvidia-opencl-dev 11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
nvidia-prime 0.8.17.1 [Ubuntu/jammy main]
nvidia-profiler 11.5.114~11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
nvidia-settings 510.47.03-0ubuntu1 [Ubuntu/jammy main]
nvidia-utils-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
nvidia-visual-profiler 11.5.114~11.5.1-1ubuntu1 [Ubuntu/jammy multiverse]
└── Extension for the nvidia-settings control panel
xserver-xorg-video-nvidia-535 535.104.05-0ubuntu0.22.04.4 [Ubuntu/jammy restricted]
```

In my testing, I sometimes saw it peak at 103W but seeing 105W in nvtop was rare. I suspect it's because of the fact that boosting is reliant on low CPU wattage to then be redirected to the GPU for better performance.

For the output of the command specified, I get:
```zsh
➜  ~ nvidia-settings -q DynamicBoostSupport


  Attribute 'DynamicBoostSupport' (Predator-PH315-54:0[gpu:0]): 1.
    'DynamicBoostSupport' is a boolean attribute; valid values are: 1 (on/true) and 0 (off/false).
    'DynamicBoostSupport' is a read-only attribute.
    'DynamicBoostSupport' can use the following target types: GPU.
```

For `nvidia-smi -q` I have the powerd-service running

``` 
   GPU Power Readings
        Power Draw                        : 18.61 W
        Current Power Limit               : 105.00 W
        Requested Power Limit             : N/A
        Default Power Limit               : 80.00 W
        Min Power Limit                   : 1.00 W
        Max Power Limit                   : 105.00 W
```

**EDIT**: Ran The Unigine Heaven Benchmark on default settings with High and my GPU appears to be outputting the rated max wattage (According to my laptop's specs provided by Acer). Idk how hard you have to work to get it to go from 104W to 105W though.  Also have my laptop's integrated display closed in favor of my 165hz gsync display and performance mode enabled (xorg runs on nvidia GPU instead of my intel)
![IMG_3714](https://github.com/snowyoneill/Linux-PredatorSense/assets/117921904/4e7f4ef6-0a42-4fdc-b5df-cb9648ed78af)

**Comment by snowyoneill** [comment]
Thank you for all this extra info! Really helpful.

So first thing i notice is that `DynamicBoostSupport` is detected on your system but not mines. So thats something i'll need to look into.

I also run the `nvidia-powerd` service but i only see a max draw of 95W. The service is definitely required in order to boost TGP but im unsure as to why i can't reach the rated max of 105W.

**Comment by snowyoneill** [comment]
I notice that we are on different os versions 22.04 vs 20.04 and also your running an updated kernel 6.2 vs 5.15

I just reread this https://download.nvidia.com/XFree86/Linux-x86_64/510.47.03/README/dynamicpowermanagement.html

Where it mentions workarounds for kernel 5.5 or lower so i should try and test on a newer Ubuntu version and see if i can unlock the remain 10W

**Comment by BrycensRanch** [comment]
Alright, best of luck!

**Comment by snowyoneill** [comment]
So i just done some testing under a live USB version of Pop!_OS 22.04 and i'm still locked at 95W.

`DynamicBoostSupport` is now registering as enabled when i query it which is something.

@BrycensRanch starting to think that one of the packages you installed somehow unlocked the remaining 10W. Haven't figured out which one is responsible yet.

Question: Do you have to enable the turbo mode in order to unlock the max wattage? ( it makes no difference on my machine )

![PopOS Dynamic](https://github.com/snowyoneill/Linux-PredatorSense/assets/4118004/27bd219e-a411-4403-9f25-5d7b5acb51f0)
![PopOS Fast](https://github.com/snowyoneill/Linux-PredatorSense/assets/4118004/5f0b1eb3-bd6c-4f51-a380-bd2b4ee7f834)
![PopOS SMI](https://github.com/snowyoneill/Linux-PredatorSense/assets/4118004/857fd25b-d95e-48a1-974c-cf93a705429b)

**Comment by BrycensRanch** [comment]
There is another package I have installed relating to turbo mode: https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module 

Once I get home, I’ll do some testing for you.

**Comment by snowyoneill** [comment]
Yeah i also have that package installed in order to change the keyboard RGB.

Does toggling the turbo affect the TGP though? From my currently testing in Linux it doesn't seem to have any effect.

**Comment by BrycensRanch** [comment]
When I was limited to 75W, it didn’t matter. However, that’s the only thing I could think of atm.

**Comment by BrycensRanch** [comment]
> @BrycensRanch starting to think that one of the packages you installed somehow unlocked the remaining 10W. Haven't figured out which one is responsible yet.

I'm honestly not too sure what packages could allow me to increase the TGP on my GPU. My GPU is in Performance mode and so is my CPU, I believe. 
![image](https://github.com/snowyoneill/Linux-PredatorSense/assets/117921904/254f2458-eed6-4b5f-b378-07679c748b93)

**Comment by snowyoneill** [comment]
Yeah im not sure its the packages either.

Not sure how you are managing to get the max TGP but im jealous lol

**Comment by snowyoneill** [comment]
Sweet baby jesus! Turns out if you restart the powed service `systemctl restart nvidia-powerd` AFTER changing the predator power profile THEN the correct wattage will be drawn! Finally seeing the full 105W on the GPU :)
