### ISSUE TITLE
video/details

### ISSUE THREAD

**Issue by mddm1** [snowyoneill/Linux-PredatorSense#4]
can someone PLEASE make a video or write a detailed description on how this thing can be installed? write it so even your grandma can understand because I am a super noob. Thanks

**Comment by snowyoneill** [comment]
@lennyco I can try and build a guide and add it to this repository. What favor of Linux are you using?

**Comment by snowyoneill** [comment]
Closing out.

**Comment by gator-git** [comment]
I know this does not get said enough, but thanks a lot for rewriting the PredatorSense program. I thought I would have to change the ec_probe values, since my model is the previous version of what it is designed for. But it worked !. I had to jump around some to enable the acpi_ec in the kernel since I am on Arch Linux. 

Once again, Thanks 😄

**Comment by snowyoneill** [comment]
@DTRGator not a problem buddy! 🙂 I'm glad it's working for you and it would seem 99% of people that have tried it.

Feel free to document any of the extra steps you had jump through in order to get it to work for Arch here and I can include it in the readme.

Cheers

**Comment by gator-git** [comment]
I will probably try creating a pull request with the added changes so that you don't have to put more effort into it, this being the first time me working with git, it's bound to take a moment 😆  . I have a couple of exams coming up this week, I'll do it after that 😄 . 

Cheers

**Comment by snowyoneill** [comment]
Haha all good. If you need any help just ping me, and best of luck with the exams!
